[sysimage]
# exclude=[]   # Additional packages to be exlucded in the system image
# statements_files=[]  # Precompile statements files to be used, relative to the project folder
execution_files = ["scripts/test/runtests.jl"] # Precompile execution files to be used, relative to the project folder