name = "InflationEvalTools"
uuid = "c8159cd7-64f9-4384-8ead-7bb45476a60a"
authors = ["Rodrigo Chang <rrcp777@gmail.com> and contributors"]
version = "0.2.0"

[deps]
CPIDataBase = "e4c88d09-b53c-432a-84e8-7deb46235234"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
InflationFunctions = "1672e640-55d7-4545-bfdd-2ddb9b2bdcf6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
